### ISSUE TITLE
`SharedArrayBuffer` changes in Chrome 91+

### ISSUE THREAD

**Issue by Richienb** [browserify/node-util#58]
In Chrome 91+, a `SharedArrayBuffer` can only be created if [cross-origin isolation](https://developer.chrome.com/blog/enabling-shared-array-buffer/) is enabled.

Affected part:

https://github.com/browserify/node-util/blob/4b1c0c79790d9968eabecd2e9c786454713e200f/support/types.js#L243

A possible fix could be [falling back to `ArrayBuffer` if `window.crossOriginIsolated !== true`](https://github.com/facebook/react/pull/20831/files).

Related to https://github.com/Richienb/node-polyfill-webpack-plugin/issues/4

**Comment by ljharb** [comment]
If it's not enabled, then isn't `typeof SharedArrayBuffer` going to be `undefined`, which would mean the preceding line would cause it to return false?

**Comment by Richienb** [comment]
Oh right. In that case, the script is already prepared to work in an environment where `SharedArrayBuffer` is unavailable.

**Comment by daewigma** [comment]
@ljharb Out of curiosity, is there documentation somewhere that says the cross origin isolation restriction will be implemented by making the constructor undefined as opposed to throwing an error when attempting to use it?

Making it undefined would make sense to do if assuming people have their apps built with backwards/cross-platform compatibility in mind, but I could also see providing the constructor and having it throw an error, as it would make it much more clear what happened to it when code suddenly starts failing.

A lot of places detailing fixing this issue recommend either stopping use of SharedArrayBuffer altogether, or checking window.crossOriginIsolated before using it. I'm not sure if this is because the constructor will just throw an error, they are wanting to get rid of the deprecation warnings in the meantime, or some other reason I'm not thinking of.

**Comment by ljharb** [comment]
@daewigma yep: https://github.com/tc39/ecma262/issues/1435
